.publish:docker:backend:
    extends:
        - .publish
        - .docker
    only:
        - master
        - /^release/.*$/
    script:
        - docker pull ${DOCKER_IMAGE_TAGGED}
        - docker tag ${DOCKER_IMAGE_TAGGED} ${DOCKER_IMAGE_LATEST}
        - docker push ${DOCKER_IMAGE_LATEST}

.publish:docker:frontend:
    extends:
        - .publish
        - .docker
    script:
        - docker
            --log-level debug
            build ./src
            --pull
            -f ./src/${PROJECT_NAME}/Dockerfile
            -t ${DOCKER_IMAGE_TEST}
            --build-arg PROJECT_NAME=${PROJECT_NAME}
            --target publish
        - docker run
            --rm
            --volume ${SHARED_PATH}:/mnt/artifacts:rw
            ${DOCKER_IMAGE_TEST}
    artifacts:
        when: always
        expire_in: 30 days
        paths:
            - ${SHARED_PATH}/**/*
